#include "engine.literary.h"

#define ENGINE_MODE_SLEEP					100

#define ENGINE_DATABASE_LIST_LENGTH_MAX		512 // approx. max length, no crashes (512)

#define ENGINE_COLOR_MAP_BACKGROUND		LBR
#define ENGINE_COLOR_FACING				BL

#define ENGINE_DUS_AMOUNT					2
#define ENGINE_DUS_RESOURCE_AMOUNT			4
#define ENGINE_DUS_BUILDING_AMOUNT			2		

#define ENGINE_DUS_LIST_CREATURE			1
#define ENGINE_DUS_LIST_RESOURCE			2
#define ENGINE_DUS_LIST_BUILDING			3

#define ENGINE_DUS_SAMPLE					{0.00000001, "Sample", ENGINE_MAP_SPRITE_SAMPLE, 0, 6, 6, 3, {0, 0, 255}}
//#define ENGINE_DUS_DEFENSE					{0.00000002, "Defense", ENGINE_MAP_SPRITE_DEFENSE, 0, 8, 8, 3, {125, 0, 125}}
#define ENGINE_DUS_BUILDING					{0.00000101, "Building", ENGINE_MAP_SPRITE_BUILDING, 0, 32, 32, 4, {0, 255, 255}, 350, 225}
#define ENGINE_DUS_DIRT						{0.00001001, "Dirt", ENGINE_MAP_SPRITE_DIRT, 0, 4, 4, 2, {175 ,125, 175}}
#define ENGINE_DUS_WORM						{0.00010001, "Worm", ENGINE_MAP_SPRITE_WORM, 1, 4, 16, 2, {255, 0, 0,}}

#define ENGINE_MAP_SPRITE_SAMPLE	{X, G, B, R, G, B, R, G, B, R, G, B, R, G, B, R, G, B, R, G, B, R, G, B, X}
#define ENGINE_MAP_SPRITE_BUILDING	{BR, BR, BR, BR, BR, BR, R, R, R, BR, BR, R, G, R, BR, BR, R, R, R, BR, BR, BR, BR, BR, BR}
#define ENGINE_MAP_SPRITE_DIRT		{R, G, BR, R, G, BR, R, G, BR, R, G, BR, R, G, BR, R, G, BR, R, G, BR, R, G, BR, R}
#define ENGINE_MAP_SPRITE_WORM		{R, G, B, R, G, B, R, G, B, R, G, B, R, G, B, R, G, B, R, G, B, R, G, B, R}


#define ENGINE_SPRITE_TEMPLATE			{X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}

// Square
#define ENGINE_DUS_SQUARE				{0.0000001, "Square"}
#define ENGINE_MAP_SPRITE_SQUARE_ONE	{R, B, B, B, G, X, X, X,			B, B, B, B, B, X, X, X,			B, B, B, B, B, X, X, X,			B, B, B, B, B, X, X, X,		Y, B, B, B, BL, X, X, X,		X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X}
#define ENGINE_MAP_SPRITE_SQUARE_TWO	{BL, B, B, B, R, X, X, X,			B, B, B, B, B, X, X, X,			B, B, B, B, B, X, X, X,			B, B, B, B, B, X, X, X,		G, B, B, B, Y, X, X, X,		X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X}
#define ENGINE_MAP_SPRITE_SQUARE_THREE	{Y, B, B, B, BL, X, X, X,			B, B, B, B, B, X, X, X,			B, B, B, B, B, X, X, X,			B, B, B, B, B, X, X, X,		R, B, B, B, G, X, X, X,		X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X}
#define ENGINE_MAP_SPRITE_SQUARE_FOUR	{G, B, B, B, Y, X, X, X,			B, B, B, B, B, X, X, X,			B, B, B, B, B, X, X, X,			B, B, B, B, B, X, X, X,		BL, B, B, B, R, X, X, X,		X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X}
#define ENGINE_MAP_ANIMATION_SQUARE		{4, ENGINE_MAP_SPRITE_SQUARE_ONE, ENGINE_MAP_SPRITE_SQUARE_TWO, ENGINE_MAP_SPRITE_SQUARE_THREE, ENGINE_MAP_SPRITE_SQUARE_FOUR}

// Defense
#define ENGINE_DUS_DEFENSE				{0.0000002, "Defense", 2}
#define ENGINE_MAP_SPRITE_DEFENSE		{GR, GR, GR, GR, GR, X, X, X,		GR, DGR, DGR, DGR, GR, X, X, X,	GR, DGR, B, DGR, GR, X, X, X,		X, GR, DGR, GR, X, X, X, X,		X, X, GR, X, X, X, X, X,		X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X}

// Offense
#define ENGINE_DUS_OFFENSE				{0.0000003, "Offense", 1}
#define ENGINE_MAP_SPRITE_OFFENSE_ONE	{X, X, GR, LGR, X, X, X, X,		X, GR, LGR, X, GR, X, X, X,		LGR, X, DGR, DGR, LGR, GR, X, X,	GR, LGR, DGR, DGR, X, LGR, X, X,	X, GR, X, LGR, GR, X, X, X,		X, X, LGR, GR, X, X, X, X,	X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X}
#define ENGINE_MAP_SPRITE_OFFENSE_TWO	{X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}
#define ENGINE_MAP_ANIMATION_OFFENSE	{1, ENGINE_MAP_SPRITE_OFFENSE_ONE}

// Grass 

#define ENGINE_MAP_SPRITE_PLANT			{X, X, DG, X, X, X, X, X, 	DG, G, X, X, X, X, X, X, 	X, LG, X, X, X, X, X, X, 	BRN, BRN, BRN, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}
#define ENGINE_MAP_SPRITE_PLANT_WATERED	{X, X, DG, X, X, X, X, X, 	DG, G, X, X, X, X, X, X, 	X, LG, X, X, X, X, X, X, 	BRN, BRN, BRN, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}

// Berry
#define ENGINE_MAP_SPRITE_BERRY			{X, R, R, R, X, X, X, X, 	R, DR, DR, DR, R, X, X, X, 	R, DR, DR, R, R, X, X, X, 	R, DR, R, R, R, X, X, X, 	X, R, R, R, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}

// Stone
#define ENGINE_MAP_SPRITE_STONE			{DGR, GR, X, X, X, X, X, X, 	GR, DGR, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}

// Currency
#define ENGINE_MAP_SPRITE_CURRENCY		{X, X, X, DGR, DGR, X, X, X, 	X, X, DGR, PNK, PNK, DGR, X, X, 	X, DGR, PNK, PNK, PNK, PNK, DGR, X, 	DGR, GR, PNK, PNK, PNK, PNK, GR, DGR, 	DGR, DPNK, GR, GR, GR, GR, DPNK, DGR, 	X, DGR, DPNK, DPNK, DPNK, DPNK, DGR, X, 	X, X, DGR, DPNK, DPNK, DGR, X, X, 	X, X, X, DGR, DGR, X, X, X}

#define ENGINE_DUS_MOVE					{0.0000004, "Move", 1}

// Background
#define ENGINE_MAP_BACKGROUND_NONE		{R, W, W, W, W, W, W, W,			W, W, W, W, W, W, W, W,			W, W, W, W, W, W, W, W, 			W, W, W, W, W, W, W, W,		W, W, W, W, W, W, W, W,		W, W, W, W, W, W, W, W,		W, W, W, W, W, W, W, W,		W, W, W, W, W, W, W, BL}
#define ENGINE_MAP_BACKGROUND_DESOLATE		{R, LBR, LBR, LBR, LBR, LBR, LBR, LBR,			LBR, LBR, LBR, LBR, LBR, LBR, LBR, LBR,			LBR, LBR, LBR, LBR, LBR, LBR, LBR, LBR, 			LBR, LBR, LBR, LBR, LBR, LBR, LBR, LBR,		LBR, LBR, LBR, LBR, LBR, LBR, LBR, LBR,		LBR, LBR, LBR, LBR, LBR, LBR, LBR, LBR,		LBR, LBR, LBR, LBR, LBR, LBR, LBR, LBR,		LBR, LBR, LBR, LBR, LBR, LBR, LBR, BL}
#define ENGINE_MAP_BACKGROUND_MEADOW		{DG, DG, DG, DG, DG, DG, DG, DG,	DG, DG, DG, DG, DG, DG, DG, DG,		DG, DG, DG, DG, DG, DG, DG, DG,		DG, DG, DG, DG, DG, DG, DG, DG,		DG, DG, DG, DG, DG, DG, DG, DG,		DG, DG, DG, DG, DG, DG, DG, DG,		DG, DG, DG, DG, DG, DG, DG, DG,		DG, DG, DG, DG, DG, DG, DG, DG}
#define ENGINE_MAP_BACKGROUND_SWAMP			{DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL, 			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL, 			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL}
#define ENGINE_MAP_BACKGROUND_SWAMP_SOUTH	{R, DBL, DBL, DBL, DBL, DBL, DBL, R, 			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL, 			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		R, DBL, DBL, DBL, DBL, DBL, DBL, R}
#define ENGINE_MAP_BACKGROUND_SWAMP_NORTH	{G, DBL, DBL, DBL, DBL, DBL, DBL, G, 			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL, 			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		G, DBL, DBL, DBL, DBL, DBL, DBL, G}
#define ENGINE_MAP_BACKGROUND_SWAMP_WEST	{BL, DBL, DBL, DBL, DBL, DBL, DBL, BL, 			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL, 			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		BL, DBL, DBL, DBL, DBL, DBL, DBL, BL}
#define ENGINE_MAP_BACKGROUND_SWAMP_EAST	{Y, DBL, DBL, DBL, DBL, DBL, DBL, Y, 			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL, 			DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		DBL, DBL, DBL, DBL, DBL, DBL, DBL, DBL,		Y, DBL, DBL, DBL, DBL, DBL, DBL, Y}

#define ENGINE_TYPE_CREATURE			1010
#define ENGINE_TYPE_RESOURCE			1020
#define ENGINE_TYPE_RESOURCE_PLANT		1021
#define ENGINE_TYPE_RESOURCE_BERRY		1022
#define ENGINE_TYPE_RESOURCE_STONE		1023
#define ENGINE_TYPE_RESOURCE_CURRENCY	1024
#define ENGINE_TYPE_TILE				1030
#define ENGINE_TYPE_TILE_DESOLATE		1031
#define ENGINE_TYPE_TILE_MEADOW			1032
#define ENGINE_TYPE_TILE_SWAMP			1033

#define ENGINE_D						{0.0000001, "D", ENGINE_DUS_SQUARE, ENGINE_TYPE_CREATURE, ENGINE_MAP_SPRITE_SQUARE_ONE, ENGINE_MAP_ANIMATION_SQUARE,			2, 5, 5}
#define ENGINE_CREATURE_DEFENSE			{0.0000002, "Defense", ENGINE_DUS_DEFENSE, ENGINE_TYPE_CREATURE, ENGINE_MAP_SPRITE_DEFENSE, {1, ENGINE_MAP_SPRITE_DEFENSE},		2, 5, 5}
#define ENGINE_CREATURE_OFFENSE			{0.0000003, "Offense", ENGINE_DUS_OFFENSE, ENGINE_TYPE_CREATURE, ENGINE_MAP_SPRITE_OFFENSE_ONE, ENGINE_MAP_ANIMATION_OFFENSE,	2, 6, 6}
#define ENGINE_RESOURCE_PLANT			{0.0000004, "Plant", ENGINE_DUS_DEFENSE, ENGINE_TYPE_RESOURCE_PLANT, ENGINE_MAP_SPRITE_PLANT, {1, ENGINE_MAP_SPRITE_PLANT},		2, 3, 4, 0}
#define ENGINE_RESOURCE_BERRY			{0.0000005, "Berry", ENGINE_DUS_OFFENSE, ENGINE_TYPE_RESOURCE_BERRY, ENGINE_MAP_SPRITE_BERRY, {1, ENGINE_MAP_SPRITE_BERRY},		1, 5, 5, 0}
#define ENGINE_RESOURCE_STONE			{0.0000006, "Stone", ENGINE_DUS_DEFENSE, ENGINE_TYPE_RESOURCE_STONE, ENGINE_MAP_SPRITE_STONE, {1, ENGINE_MAP_SPRITE_STONE},		2, 2, 2, 0}
#define ENGINE_RESOURCE_CURRENCY		{0.0000006, "Currency", ENGINE_DUS_DEFENSE, ENGINE_TYPE_RESOURCE_CURRENCY, ENGINE_MAP_SPRITE_CURRENCY, {1, ENGINE_MAP_SPRITE_CURRENCY},		1, 8, 8, 0}
#define ENGINE_DRAW						101
#define ENGINE_SPRITEGRAPH	{}

